### Post "Hello!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Hello!"
}

### Post "Ciao!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Ciao!"
}

### Post "Hola!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Hola!"
}

### Get messages
GET http://localhost:8080/

### Get message by id
GET http://localhost:8080/c31684e2-f572-42ba-96d0-abf72176ccdc